### ISSUE TITLE
Search in Zotero does not find results when using more than one word

### ISSUE THREAD

**Issue by kareliot** [shivams/zim-zotero-plugin#3]
The Search in Zotero dialogue does not seem to work properly in my case.
It works fine when I am just searching for the name of the author, but since I usually have lots of different entries by the same author (or worse even, by different authors with the same last name), this usually means that I have to manually delete all but one of the imported entries after pressing GO.

Another, unrelated minor issue is that I have to use the mouse to click on GO instead of just hitting enter after putting my search term in the search field.

But otherwise the plugin works really well and makes my work a lot easier – thanks a lot!

Let me know if I can help you with debugging or if you need some logs

**Comment by shivams** [comment]
Yes, using mouse to click on GO is an issue which bugs me too. I think it's time I fix it. A work-around for now is to press `TAB` key thrice to reach GO (not a clean solution, I agree). 

Regarding your other issue about searching, what you can do is that you search for the exact paper you're looking for. E.g. I have multiple authors by the name "McCarthy" in my collection. And I want a paper which has a keyword "century" in its title. Then, if I search for `mccarthy+century`, it will give me only that paper. Note that `+` sign is essential and `mccarthy century` will not work. I think I should document this. 

Let me know if this helps in your searching issue :)

And thank you for your offer on debugging. I actually have one issue with which I need help with!

Could you confirm me if the plugin works on Windows? I am referring to this issue: https://github.com/shivams/zim-zotero-plugin/issues/2. You can respond on that issue, instead of replying here. I am unable to get hold of any Windows machine to check the issue.

**Comment by kareliot** [comment]
Thanks for the quick reply!
The tip with the + sign is really great – that actually helps a lot. And yes, it would probably be helpful for others too if that was documented somewhere ;)
And using tab is still better than having to use the mouse – haven’t thought about that.

I am sorry, can’t really help you with the other issue, I am on linux and don’t have a windows machine either.
